---
- name: pulling info from switches
  hosts: eosswitches
  gather_facts: no

  vars:
          ansible_connection: network_cli
          ansible_network_os: eos
          ansible_become: yes
          ansible_become_method: enable
          ansible_user: admin
          ansible_ssh_pass: alta3

  tasks:
          - name: Collect all facts
            eos_facts:
                  gather_subset: all

          - name: redirect to a file
            copy:
                    content: "{{ ansible_facts.net_config}}"
                    dest: ~/configs.txt

          - name: show
            debug:
                    var: ansible_facts.net_config
...
